#!/bin/bash
CHOICE=$(echo -e "Chrome\nChromium\nFirefox\nOpera" | dmenu -h 27 \
	-x 0 -y 0 -w 1920 \
	-nb '#212121' \
	-nf '#cccccc' \
	-sb '#78a878' \
	-sf '#ffffff' \
	-fn 'Ubuntu-9' -i -p "$1")


if [ "$CHOICE" == "Chrome" ]; then
    google-chrome-stable
elif [ "$CHOICE" == "Chromium" ]; then
    chromium
elif [ "$CHOICE" == "Firefox" ]; then
	firefox
elif [ "$CHOICE" == "Opera" ]; then
    opera
else
	exit 0
fi