#!/bin/bash
theme="/home/${USER}/ZDotfiles/rofi/sp.theme.rasi"
chosen=$(echo -e "Chrome\nChromium\nFirefox\nOpera" | rofi -dmenu -theme ${theme})

if [ "$chosen" == "Chrome" ]; then
	notify-send -a "Browser Launcher" "$chosen" --expire-time=3000 &
	google-chrome &
elif [ "$chosen" == "Chromium" ]; then
	notify-send -a "Browser Launcher" "$chosen" --expire-time=3000 &
	chromium &
elif [ "$chosen" == "Firefox" ]; then
	notify-send -a "Browser Launcher" "$chosen" --expire-time=3000 &
	firefox &
elif [ "$chosen" == "Opera" ]; then
	notify-send -a "Browser Launcher" "$chosen" --expire-time=3000 &
	opera &
else
	exit 0
fi
