#!/usr/bin/env bash

count=0
disconnected="Disconnected"
wireless_connected="Connected"
ethernet_connected="Connected"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com) &>/dev/null; then
        if [[ $ID == e* ]]; then
            PING=$(ping -i 0.3 -c 2 google.com | tail -n 1 | cut -d '/' -f5 | cut -d '.' -f1)
            LATENCY="${PING}ms"
            echo "$LATENCY" ; sleep 25
        else
            echo "$wireless_connected" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
