setxkbmap us

if [ -f "${HOME}"/.npmkey ]; then
  source "${HOME}"/.npmkey
fi

if [ -f "${HOME}"/.gptkey ]; then
  source "${HOME}"/.gptkey
fi

if [ -f "${HOME}"/.azure_marketplace ]; then
  source "${HOME}"/.azure_marketplace
fi

EMSCRIPTENPATH="$HOME/.emsdk"
export EMSCRIPTENPATH="$EMSCRIPTENPATH"
export PATH=$PATH:$EMSCRIPTENPATH
export PATH=$PATH:$EMSCRIPTENPATH/upstream/emscripten
export QT_QPA_PLATFORMTHEME=qt6ct

if [ -d "$EMSCRIPTENPATH" ]; then
  source $EMSCRIPTENPATH/emsdk_env.sh > /dev/null 2>&1
fi

start_tmux() {
  if [[ -n "$TMUX" && -z "$1" ]]; then
    echo && neofetch
    return
  fi

  if [[ -n "$TMUX" ]]; then
    return
  fi

  if [[ "$TERM" != "xterm-ghostty" ]]; then
    return
  fi

  if [[ -z "$TMUX" && -o interactive ]]; then
    ~/ZDotfiles/scripts/startmux
  fi
}
# start_tmux "$@"
echo && neofetch

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
autoload -Uz compinit
compinit

plugins=(git)

source $ZSH/oh-my-zsh.sh

export ME="/home/$(whoami)"
export DOTFILESPATH="ZDotfiles"
export GOPATH="$ME/.go"
export ODINPATH="$ME/.odin"
export PATH=$PATH:$HOME/${DOTFILESPATH}/scripts
export PATH=$PATH:$HOME/${DOTFILESPATH}/bin
export PATH=$PATH:$HOME/${DOTFILESPATH}/depot_tools
export PATH=$PATH:$HOME/.zig
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.odin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/share/yabridge
export PAGER="most"
export DOTFILES=$DOTFILESPATH

if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias tmux='tmux -2'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

if [ -f $ME/.cargo/bin/exa ]; then
  alias ll='exa -bghHlS --git'
  alias la='exa -bghHlSa --git'
else
  alias ll='ls -hl --color=auto'
  alias la='ls -hlA --color=auto'
fi

alias vim='nvim'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -d "$HOME/.powerlevel10k" ]; then
  source ~/.powerlevel10k/powerlevel10k.zsh-theme
fi

if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
